extends:
  - stylelint-config-standard-scss
  - stylelint-config-clean-order

plugins:
  - stylelint-scss
  - stylelint-prettier

rules:
  # Enable prettier
  prettier/prettier: true

  # Disallow !important within declarations
  declaration-no-important: true

  # Expected class pattern to be BEM style
  selector-class-pattern: ^([a-z][a-z0-9]*)(-[a-z0-9]+)*((__([a-z][a-z0-9]*)(-[a-z0-9]+)*)?(--([a-z][a-z0-9]*)(-[a-z0-9]+)*)?)$

  # The following prefix rules are enabled since we use autoprefixer
  at-rule-no-vendor-prefix: true
  media-feature-name-no-vendor-prefix: true
  value-no-vendor-prefix: true
  selector-no-vendor-prefix:
    - true
    - ignoreSelectors: [/-moz-.*/]

  # Usually if you're nesting past 3 levels deep there's a problem
  max-nesting-depth:
    - 2
    - ignore:
        - blockless-at-rules
      ignoreAtRules:
        - media

  # Specify percentage or number notation for alpha-values
  alpha-value-notation: number

  # Some not depricated rules from https://github.com/htmlacademy/stylelint-config-htmlacademy
  annotation-no-unknown: true
  color-no-invalid-hex: true
  font-family-no-missing-generic-family-keyword: true
  function-calc-no-unspaced-operator: true
  function-no-unknown:
    - true
    - ignoreFunctions:
        - fade
  custom-property-no-missing-var-function: true
  keyframe-declaration-no-important: true
  keyframe-block-no-duplicate-selectors: true
  declaration-block-no-duplicate-properties: true

  no-descending-specificity: null
  no-duplicate-at-import-rules: true
  no-invalid-position-at-import-rule: true
  color-hex-alpha: never
  color-named: never
  color-no-hex: null
  length-zero-no-unit:
    - true
    - ignore:
        - custom-properties
      ignoreFunctions:
        - /^--/
  font-family-name-quotes: always-unless-keyword
  font-weight-notation:
    - numeric
    - ignore:
        - relative
  function-url-quotes: always
  import-notation: null
  keyframe-selector-notation: percentage-unless-within-keyword-only-block
  number-max-precision: 2
  property-disallowed-list: null
  property-no-vendor-prefix: true
  declaration-property-max-values: null
  selector-attribute-quotes: always
  selector-max-id: 0
  selector-max-universal: 2
  selector-not-notation: simple
  selector-pseudo-element-colon-notation: double
  rule-selector-property-disallowed-list: null

  value-keyword-case:
    - lower
    - camelCaseSvgKeywords: true
  function-name-case: lower
  selector-type-case: lower
  rule-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - after-comment
  at-rule-empty-line-before:
    - always
    - except:
        - first-nested
        - blockless-after-blockless
      ignore:
        - after-comment
