extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss

plugins:
  - stylelint-scss
  - stylelint-order

rules:
  # Disallow !important within declarations
  declaration-no-important: true

  # Expected class pattern to be BEM style
  selector-class-pattern: "^([a-z][a-z0-9]*)(-[a-z0-9]+)*((__([a-z][a-z0-9]*)(-[a-z0-9]+)*)?(--([a-z][a-z0-9]*)(-[a-z0-9]+)*)?)$"

  # The following prefix rules are enabled since we use autoprefixer
  at-rule-no-vendor-prefix: true
  media-feature-name-no-vendor-prefix: true
  value-no-vendor-prefix: true
  selector-no-vendor-prefix:
    - true
    - ignoreSelectors: ["/-moz-.*/"]

  # Usually if you're nesting past 3 levels deep there's a problem
  max-nesting-depth:
    - 2
    - ignore: "blockless-at-rules"
    - ignoreAtRules:
        - media

  # Some not depricated rules from https://github.com/htmlacademy/stylelint-config-htmlacademy
  annotation-no-unknown: true
  color-no-invalid-hex: true
  font-family-no-missing-generic-family-keyword: true
  function-calc-no-unspaced-operator: true
  function-no-unknown:
    - true
    - ignoreFunctions:
        - fade
  custom-property-no-missing-var-function: true
  keyframe-declaration-no-important: true
  keyframe-block-no-duplicate-selectors: true
  declaration-block-no-duplicate-properties: true
  selector-type-no-unknown: true
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - mixin
        - define-mixin
        - include
        - content
        - rules
        - each
  no-descending-specificity: null
  no-duplicate-at-import-rules: true
  no-invalid-position-at-import-rule: true
  color-hex-alpha: never
  color-named: never
  color-no-hex: null
  length-zero-no-unit:
    - true
    - ignore:
        - custom-properties
      ignoreFunctions:
        - /^--/
  font-family-name-quotes: always-unless-keyword
  font-weight-notation:
    - numeric
    - ignore:
        - relative
  function-url-quotes: always
  import-notation: null
  keyframe-selector-notation: percentage-unless-within-keyword-only-block
  number-max-precision: 2
  property-disallowed-list: null
  property-no-vendor-prefix: true
  declaration-property-max-values: null
  selector-attribute-quotes: always
  selector-max-id: 0
  selector-max-universal: 2
  selector-not-notation: simple
  selector-pseudo-element-colon-notation: double
  rule-selector-property-disallowed-list: null

  value-keyword-case:
    - lower
    - camelCaseSvgKeywords: true
  function-name-case: lower
  selector-type-case: lower
  rule-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - after-comment
  at-rule-empty-line-before:
    - always
    - except:
        - first-nested
        - blockless-after-blockless
      ignore:
        - after-comment

  # Specify the order of properties within declaration blocks
  order/properties-order:
    # Positioning
    - all
    - position
    - top
    - right
    - bottom
    - left
    - inset
    - inset-block
    - inset-block-start
    - inset-block-end
    - inset-inline
    - inset-inline-start
    - inset-inline-end
    - z-index

    # Block
    - display
    - grid-template
    - grid-template-rows
    - grid-template-columns
    - grid-template-areas
    - grid-auto-rows
    - grid-auto-columns
    - grid-auto-flow
    - grid-area
    - grid-row
    - grid-row-start
    - grid-row-end
    - grid-column
    - grid-column-start
    - grid-column-end
    - flex
    - flex-grow
    - flex-shrink
    - flex-basis
    - flex-flow
    - flex-direction
    - flex-wrap
    - justify-content
    - justify-self
    - justify-items
    - align-content
    - align-items
    - align-self
    - gap
    - row-gap
    - columns
    - column-count
    - column-fill
    - column-gap
    - column-rule
    - column-rule-color
    - column-rule-style
    - column-rule-width
    - column-span
    - column-width
    - order
    - float
    - clear
    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left
    - margin-block-start
    - margin-block-end
    - margin-inline-start
    - margin-inline-end
    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left
    - padding-block-start
    - padding-block-end
    - padding-inline-start
    - padding-inline-end
    - box-sizing
    - width
    - min-width
    - max-width
    - inline-size
    - min-inline-size
    - max-inline-size
    - height
    - min-height
    - max-height
    - block-size
    - min-block-size
    - max-block-size
    - overflow
    - overflow-x
    - overflow-y

    # Decoration
    - box-shadow
    - outline
    - outline-width
    - outline-style
    - outline-color
    - outline-offset
    - border
    - border-width
    - border-style
    - border-color
    - border-top
    - border-top-width
    - border-top-style
    - border-top-color
    - border-block-start
    - border-block-start-width
    - border-block-start-style
    - border-block-start-color
    - border-bottom
    - border-bottom-width
    - border-bottom-style
    - border-bottom-color
    - border-block-end
    - border-block-end-width
    - border-block-end-style
    - border-block-end-color
    - border-left
    - border-left-width
    - border-left-style
    - border-left-color
    - border-inline-start
    - border-inline-start-width
    - border-inline-start-style
    - border-inline-start-color
    - border-right
    - border-right-width
    - border-right-style
    - border-right-color
    - border-inline-end
    - border-inline-end-width
    - border-inline-end-style
    - border-inline-end-color
    - border-radius
    - border-top-left-radius
    - border-top-right-radius
    - border-bottom-right-radius
    - border-bottom-left-radius
    - border-start-start-radius
    - border-start-end-radius
    - border-end-end-radius
    - border-end-start-radius
    - border-image
    - border-image-source
    - border-image-slice
    - border-image-width
    - border-image-outset
    - border-image-repeat
    - border-collapse
    - border-spacing
    - stroke
    - stroke-dasharray
    - stroke-dashoffset
    - stroke-linecap
    - stroke-linejoin
    - stroke-miterlimit
    - stroke-opacity
    - stroke-width
    - background
    - background-color
    - background-image
    - background-position
    - background-position-x
    - background-position-y
    - background-size
    - background-clip
    - background-origin
    - background-attachment
    - background-repeat
    - background-blend-mode
    - fill
    - fill-opacity
    - fill-rule
    - color

    # Text
    - direction
    - writing-mode
    - list-style
    - list-style-position
    - list-style-type
    - list-style-image
    - text-align
    - text-align-last
    - line-height
    - text-transform
    - text-decoration
    - text-emphasis
    - text-emphasis-color
    - text-emphasis-style
    - text-emphasis-position
    - font
    - font-weight
    - font-size
    - font-family
    - font-style
    - font-display
    - font-variant
    - font-size-adjust
    - font-stretch
    - font-effect
    - font-emphasize
    - font-emphasize-position
    - font-emphasize-style
    - font-smooth
